import { Router } from "express";
import { addBoard, deleteBoard, getBoard, getBoards, updateBoard, } from "../controllers/board.controller.js";
import { addCard, deleteCard, moveCard, updateCard, } from "../controllers/card.controller.js";
import { addColumn, deleteColumn, updateColumn, } from "../controllers/column.controller.js";
import { authMiddleware } from "../middlewares/auth.middleware.js";
const router = Router();
router.use(authMiddleware);
router.get("/boards", getBoards);
router.get("/boards/:id", getBoard);
router.post("/boards", addBoard);
router.put("/boards", updateBoard);
router.delete("/boards/:id", deleteBoard);
router.post("/columns", addColumn);
router.put("/columns", updateColumn);
router.delete("/columns", deleteColumn);
router.post("/cards", addCard);
router.put("/cards", updateCard);
router.delete("/cards", deleteCard);
router.put("/cards/move", moveCard);
export { router };
